import type { GameState } from '../types'
import type { EventDef } from './events'
import { atIntl, clubTier, isBenched, isPre, isPro, isStarter, macroOf } from './story'

const fans = (s: GameState, n: number) => s.me!.fans >= n
const age = (s: GameState) => s.players[s.me!.id]?.age ?? 18
const streams = (s: GameState) => s.me!.stream.total >= 3

/**
 * The rest of the pool, by where the career is: the ladder and the café, the
 * second tier, a league, the trips abroad, the bench, a contract's last year,
 * the years when the reactions start to go. Same rules as events.ts — every
 * option costs something somewhere and leans on one of the four axes — and
 * the same effects, so nothing here needs a new rule to settle.
 *
 * Region colour only where it is true: the 加速器 before China had its own
 * server, the server opening in July 2023, English on EMEA comms, Twitch
 * after practice in the Americas, handwritten cards at Pacific venues, the
 * last training day before the New Year.
 */
export const MORE_EVENTS: EventDef[] = [
  // ---- the ladder years
  { id: 'pre_vpn', w: 5, max: 2, rec: 2, when: (s) => isPre(s) && macroOf(s) === 'China' && s.year <= 2022,
    q: '加速器半夜又断了，这把排位直接判负。', ctx: '亚服的延迟本来就在六十上下。',
    a: [{ t: '换一家贵点的加速器', g: 'grind', e: { money: -400, ladder: 1 } },
      { t: '等凌晨三点人少再打', g: 'hard', e: { fatigue: 8, ladder: 2, form: -1 } },
      { t: '今晚不排了，看职业比赛录像', g: 'warm', e: { ladder: -1, xp: { awareness: 12 } } }] },
  { id: 'cn_server', w: 12, max: 1, rec: 1, when: (s) => macroOf(s) === 'China' && s.year === 2023 && s.day >= 191 && s.day <= 260,
    q: '国服开服了，所有人的段位从头打。', ctx: '第一周的榜单谁都有机会上。',
    a: [{ t: '第一周就冲榜', g: 'show', e: { ladder: 3, fatigue: 10, heat: 15 } },
      { t: '先练枪，等手感稳了再冲', g: 'grind', e: { xp: { aim: 12 }, ladder: -1 } }] },
  { id: 'pre_fill', w: 5, max: 2, rec: 0, when: (s) => isPre(s) && s.me!.pre.ladder >= 50,
    q: '一支二线队训练赛缺人，临时叫你去补位。', ctx: '他们缺的不是你打的位置。',
    a: [{ t: '去，打不熟的位置', g: 'hard', e: { fatigue: 6, xp: { utility: 10, teamwork: 8 }, scoutSeen: 1 }, seed: 'fill:off' },
      { t: '去，但只打自己的位置', g: 'show', e: { fatigue: 4, xp: { aim: 8 } }, seed: 'fill:own' },
      { t: '不去，这周要冲分', g: 'grind', e: { ladder: 1 } }] },
  { id: 'cheat_accuse', w: 5, max: 1, rec: 1, when: (s) => isPre(s) && s.me!.pre.ladder >= 40,
    q: '一个输给你的人在论坛发帖，说你开挂。', ctx: '帖子下面有人把你的击杀集锦一帧一帧放慢了。',
    a: [{ t: '开手部摄像头直播自证', g: 'show', e: { heat: 20, fatigue: 4 }, seed: 'cheat:cam' },
      { t: '不理，继续排', g: 'grind', e: { tilt: 4, ladder: 1 }, seed: 'cheat:quiet' },
      { t: '回帖对骂', g: 'hard', e: { heat: 15, tilt: 8 }, seed: 'cheat:fight' }] },
  { id: 'pre_vod_roast', w: 5, max: 2, rec: 0, when: isPre,
    q: '你把自己的排位录像发到论坛求点评，被说得一文不值。', ctx: '有几条确实说到了点子上。',
    a: [{ t: '逐条对着改', g: 'grind', e: { xp: { awareness: 14 }, tilt: 6 } },
      { t: '回帖跟他们吵', g: 'hard', e: { heat: 12, tilt: 8 } },
      { t: '关掉帖子，接着排', g: 'warm', e: { tilt: -3, ladder: 1 } }] },
  { id: 'pre_five', w: 5, max: 1, rec: 1, when: (s) => isPre(s) && s.me!.pre.ladder >= 45,
    q: '网吧里认识的四个人想跟你组固定车队，一起报杯赛。', ctx: '其中两个的枪法比你差一截。',
    a: [{ t: '组，五个人一起练', g: 'warm', e: { xp: { teamwork: 12, communication: 8 }, ladder: -1 } },
      { t: '只一起打杯赛，平时各排各的', g: 'grind', e: { xp: { teamwork: 5 }, ladder: 1 } },
      { t: '不组，等更强的车队', g: 'hard', e: { ladder: 2, mental: -1 } }] },
  { id: 'pre_exam', w: 5, max: 1, rec: 0, when: (s) => isPre(s) && s.me!.pre.year === 1 && age(s) <= 18,
    q: '学校的期末考试就在这周。', ctx: '班主任已经给你家里打过两次电话了。',
    a: [{ t: '去考，这周不排位', g: 'warm', e: { ladder: -2, mental: 2, tilt: -6 } },
      { t: '请假，继续冲分', g: 'hard', e: { ladder: 2, mental: -1 } }] },

  // ---- the second tier
  { id: 'chal_vct_scrim', w: 5, max: 2, rec: 1, when: (s) => clubTier(s) === 2,
    q: '一支一级联赛的队约你们打训练赛，你们被打成 3 比 13。', ctx: '散场前，对面和你同位置的选手还在复盘。',
    a: [{ t: '过去问他那几个回合怎么想的', g: 'warm', e: { xp: { awareness: 14 }, mental: -1 }, seed: 'askpro:yes' },
      { t: '回去自己看录像', g: 'grind', e: { xp: { utility: 10 }, tilt: 3 } },
      { t: '今晚打排位发泄一下', g: 'hard', e: { tilt: -4, form: 1, fatigue: 5 } }] },
  { id: 'chal_road', w: 4, max: 3, rec: 0, when: (s) => clubTier(s) === 2,
    q: '线下赛在另一座城市，最早的一班车凌晨出发。', ctx: '比赛在当天下午。',
    a: [{ t: '车上睡', g: 'warm', e: { fatigue: 6, bond: 4 } },
      { t: '自己掏钱提前一天去', g: 'grind', e: { money: -800, fatigue: -4, form: 1 } },
      { t: '车上把对手录像看完', g: 'hard', e: { fatigue: 9, xp: { awareness: 10 } } }] },
  { id: 'chal_ascend', w: 4, max: 2, rec: 1, when: (s) => clubTier(s) === 2 && s.year >= 2023,
    q: '队里有人把升级赛的对阵表贴在了训练室墙上。', ctx: '离一级联赛只差这几场。',
    a: [{ t: '每天加一场训练赛', g: 'grind', e: { fatigue: 8, xp: { teamwork: 10 }, coachTrust: 3 } },
      { t: '把表撕下来，一场一场打', g: 'warm', e: { tilt: -8, mental: 1 } },
      { t: '在直播里立 flag', g: 'show', e: { heat: 25, tilt: 5 } }] },

  // ---- a league, and where it is played
  { id: 'vct_lights', w: 8, max: 1, rec: 0, when: (s) => clubTier(s) === 1 && s.year >= 2023 && isStarter(s) && s.me!.seasonStart.starts <= 3,
    q: '第一次在联赛场馆打正赛，灯光打下来，你的手在抖。', ctx: '观众的声音隔着耳机也听得见。',
    a: [{ t: '深呼吸，按训练赛的节奏打', g: 'grind', e: { mental: 1, form: -1 } },
      { t: '多跟队友说话，把紧张说出去', g: 'warm', e: { bond: 5, xp: { communication: 6 } } },
      { t: '想打几个高光', g: 'show', e: { heat: 20, form: 2, tilt: 5 } }] },
  { id: 'emea_english', w: 5, max: 1, rec: 1, when: (s) => isPro(s) && macroOf(s) === 'EMEA' && s.year >= 2023,
    q: '队里的语音统一说英语，不是每个人的母语。', ctx: '你报点总慢半拍。',
    a: [{ t: '每天加一小时英语', g: 'grind', e: { fatigue: 5, xp: { communication: 14 } } },
      { t: '请队友教你二十个关键词', g: 'warm', e: { bond: 6, xp: { communication: 6 } } },
      { t: '只报点，别的不说', g: 'hard', e: { form: 1, bond: -3 } }] },
  { id: 'amer_stream', w: 4, max: 2, rec: 2, when: (s) => isPro(s) && macroOf(s) === 'Americas',
    q: '队友下了训练就在 Twitch 上播排位，观众比有的比赛还多。', ctx: '他问你要不要一起开。',
    a: [{ t: '一起开', g: 'show', e: { heat: 25, fatigue: 5, bond: 4 } },
      { t: '下了训练就睡', g: 'grind', e: { fatigue: -5 } },
      { t: '陪他打，不开播', g: 'warm', e: { bond: 6, form: 1, fatigue: 3 } }] },
  { id: 'pac_cards', w: 4, max: 2, rec: 2, when: (s) => isPro(s) && macroOf(s) === 'Pacific' && fans(s, 60),
    q: '场馆外排队的粉丝给每个选手准备了手写卡片，一人一叠。', ctx: '有几张是用你的母语写的。',
    a: [{ t: '每一张都回', g: 'warm', e: { fatigue: 5, mental: 2, heat: 10 } },
      { t: '拍一段致谢视频', g: 'show', e: { heat: 25 } },
      { t: '收好，打完赛段再看', g: 'grind', e: { mental: 1, tilt: -3 } }] },
  { id: 'cn_newyear', w: 10, max: 3, rec: 1, when: (s) => isPro(s) && macroOf(s) === 'China' && s.day >= 18 && s.day <= 45,
    q: '年前最后一个训练日，基地里只剩你和教练。', ctx: '回家的车票是明天早上的。',
    a: [{ t: '改签，再练两天', g: 'grind', e: { xp: { aim: 10, utility: 6 }, mental: -1, fatigue: 6 } },
      { t: '按时回家过年', g: 'warm', e: { fatigue: -12, tilt: -10, form: -2 } },
      { t: '带着外设回家，在网吧接着练', g: 'hard', e: { money: -300, xp: { aim: 8 }, fatigue: -4 } }] },

  // ---- abroad for an international
  { id: 'intl_jetlag', w: 10, max: 4, rec: 0, when: atIntl,
    q: '落地第二天，凌晨四点你就醒了，再也睡不着。', ctx: '比赛在当地时间下午。',
    a: [{ t: '去酒店健身房出一身汗', g: 'grind', e: { fatigue: 2, form: 2 } },
      { t: '吃药强行睡回去', g: 'warm', e: { fatigue: -8, form: -2 } },
      { t: '反正醒着，把对手录像看完', g: 'hard', e: { xp: { awareness: 12 }, fatigue: 8 } }] },
  { id: 'intl_dm', w: 6, max: 2, rec: 1, when: atIntl,
    q: '酒店电梯里，另一个赛区的选手认出了你，约你晚上去他们的训练室打死斗。', ctx: '教练说过，国际赛期间别让人看太多东西。',
    a: [{ t: '去，顺便看看他们怎么练', g: 'warm', e: { fatigue: 5, xp: { aim: 10 }, coachTrust: -2 }, seed: 'intlfriend:yes' },
      { t: '婉拒，加个联系方式', g: 'grind', e: { coachTrust: 1 }, seed: 'intlfriend:card' },
      { t: '不去', g: 'hard', e: { coachTrust: 2, form: 1 } }] },
  { id: 'intl_crowd', w: 6, max: 2, rec: 1, when: (s) => atIntl(s) && isStarter(s),
    q: '登台的时候，场馆里一大半观众在为对面喊。', ctx: '声音大到语音里都听不清。',
    a: [{ t: '冲观众比了个安静的手势', g: 'show', e: { heat: 40, tilt: 4, coachTrust: -2 } },
      { t: '把耳机音量调大，只听队友', g: 'grind', e: { tilt: -4, form: 1 } },
      { t: '当成动力', g: 'hard', e: { mental: 1, tilt: 6, form: 2 } }] },

  // ---- the bench
  { id: 'bench_notes', w: 6, max: 1, rec: 0, when: isBenched,
    q: '替补的日子，分析师问你愿不愿意帮他整理对手的数据。', ctx: '每天两小时，比赛里没人看得到。',
    a: [{ t: '帮，顺便学', g: 'grind', e: { xp: { awareness: 12 }, coachTrust: 3, fatigue: 3 }, seed: 'notes:yes' },
      { t: '不了，时间留给枪法', g: 'hard', e: { xp: { aim: 12 } }, seed: 'notes:no' }] },
  { id: 'bench_stream', w: 5, max: 2, rec: 1, when: (s) => isBenched(s) && streams(s),
    q: '直播时弹幕一直在问：你为什么不上场？', ctx: '房管问要不要先关弹幕。',
    a: [{ t: '实话实说：教练的决定', g: 'hard', e: { heat: 20, coachTrust: -3 }, seed: 'benchtalk:said' },
      { t: '笑着说在练新特工', g: 'show', e: { heat: 8 } },
      { t: '关弹幕，专心打', g: 'grind', e: { heat: -5, tilt: -2 } }] },

  // ---- a contract's last year
  { id: 'contract_talk', w: 4, max: 2, rec: 1, when: (s) => isPro(s) && (s.players[s.me!.id]?.contractYears ?? 9) <= 1,
    q: '论坛上有人说你合同到期就走。', ctx: '这话你一个字都没说过。',
    a: [{ t: '发条动态辟谣', g: 'warm', e: { gmTrust: 4, heat: 10 } },
      { t: '不回应', g: 'grind', e: { tilt: 3 } },
      { t: '回一句「看情况」', g: 'show', e: { heat: 30, gmTrust: -6 } }] },

  // ---- the later years
  { id: 'vet_reaction', w: 5, max: 2, rec: 0, when: (s) => isPro(s) && age(s) >= 26,
    q: '队里做反应测试，你的成绩比去年慢了十几毫秒。', ctx: '年轻队员假装没看见。',
    a: [{ t: '把重心放到站位和道具上', g: 'grind', e: { xp: { awareness: 10, utility: 10 } } },
      { t: '加练反应，不认这个数', g: 'hard', e: { xp: { reaction: 12 }, fatigue: 10, tilt: 3 } },
      { t: '拿这件事跟年轻人开玩笑', g: 'warm', e: { bond: 6, mental: 1 } }] },
  { id: 'vet_rookie', w: 5, max: 1, rec: 0, when: (s) => isPro(s) && age(s) >= 24,
    q: '青训队上来一个 19 岁的同位置新人跟一队训练，天梯排名比你高。', ctx: '他第一天就来问你要准星代码。',
    a: [{ t: '给，顺便带他复盘', g: 'warm', e: { coachTrust: 3, mental: 1, fatigue: 3 }, seed: 'rookie:mentor' },
      { t: '训练赛里压着他打', g: 'hard', e: { xp: { aim: 10 }, form: 1, coachTrust: -1 }, seed: 'rookie:press' },
      { t: '找教练要一句准话', g: 'grind', e: { coachTrust: -3, mental: 1 } }] },
  { id: 'vet_staff', w: 4, max: 1, rec: 0, when: (s) => isPro(s) && age(s) >= 27 && s.me!.seasons.filter((x) => x.tier > 0).length >= 4,
    q: '教练私下问你：退役以后愿不愿意留下来进教练组。', ctx: '他说不急，只是先问一句。',
    a: [{ t: '说会考虑，这赛季先帮着带复盘', g: 'warm', e: { coachTrust: 5, xp: { igl: 8, awareness: 6 }, fatigue: 3 } },
      { t: '「我还能打。」', g: 'hard', e: { mental: 2, tilt: 3, form: 1 } }] },

  // ---- any year
  { id: 'map_pool', w: 5, max: 4, rec: 1, when: () => true,
    q: '地图池轮换：你最熟的一张图下池了，一张新图进来。', ctx: '职业圈还没人打出答案。',
    a: [{ t: '第一周就把新图点位摸透', g: 'grind', e: { fatigue: 8, xp: { utility: 12, awareness: 6 } } },
      { t: '先看别人怎么打', g: 'warm', e: { xp: { awareness: 8 } } },
      { t: '在排位里硬摸，边打边学', g: 'hard', e: { xp: { aim: 6, utility: 6 }, tilt: 4, form: -1 } }] },
  { id: 'crosshair', w: 4, max: 1, rec: 2, when: (s) => fans(s, 100),
    q: '你的准星代码被人扒了出来，天梯里一堆人在用同款。', ctx: '私信里全是问灵敏度的。',
    a: [{ t: '做一期设置分享', g: 'show', e: { heat: 25, fatigue: 3 } },
      { t: '换个新准星，找回自己的感觉', g: 'hard', e: { form: -2, xp: { aim: 8 } } },
      { t: '不理', g: 'grind', e: { mental: 1 } }] },
  { id: 'ranked_mate', w: 5, max: 3, rec: 1, when: isPro,
    q: '排位里撞上自己队友在对面，他赢了，还在全体频道发了个表情。', ctx: '明天训练赛你们一队。',
    a: [{ t: '训练赛里找回来', g: 'hard', e: { xp: { aim: 10 }, bond: -3, form: 1 } },
      { t: '截图发队群玩梗', g: 'show', e: { bond: 5, heat: 5 } },
      { t: '拉他双排', g: 'warm', e: { bond: 6, fatigue: 4 } }] },
  { id: 'igl_sick', w: 4, max: 2, rec: 1, when: (s) => isStarter(s) && !s.players[s.me!.id]?.isIgl,
    q: '指挥嗓子哑了，教练问你今天训练赛能不能替他喊。', ctx: '五个人都在等你开口。',
    a: [{ t: '接，喊错了算我的', g: 'hard', e: { xp: { igl: 14, communication: 6 }, form: -1, coachTrust: 3 } },
      { t: '让经验更多的队友来', g: 'warm', e: { bond: 3 } },
      { t: '只管自己的位置', g: 'grind', e: { form: 1 } }] },

  // ---- 回响: cards that come back for an earlier choice (me/storyweek.ts ECHOES)
  { id: 'echo_boost', w: 0, max: 1, rec: 0, echo: 'boost', when: isPro,
    q: '有人翻出了你当年接代练的记录，截图在论坛上传开了。', ctx: '那一单你确实接了。现在你是职业选手。',
    a: [{ t: '公开道歉', g: 'warm', e: { heat: 15, fans: -20, gmTrust: -2, tilt: -4 } },
      { t: '不承认', g: 'hard', e: { heat: 35, gmTrust: -8, tilt: 8 } },
      { t: '交给俱乐部处理', g: 'grind', e: { gmTrust: -4, coachTrust: -2 } }] },
  { id: 'echo_cheat_cam', w: 0, max: 1, rec: 1, echo: 'cheat', when: () => true,
    q: '当年你开手部摄像头自证的那段录像被翻了出来，剪成了集锦。', ctx: '标题是「从被说开挂，到打职业」。',
    a: [{ t: '转发，配一句「还在练」', g: 'show', e: { heat: 30, fans: 20 } },
      { t: '不提旧事', g: 'grind', e: { mental: 1, tilt: -3 } }] },
  { id: 'echo_cheat_old', w: 0, max: 1, rec: 2, echo: 'cheat', when: isPro,
    q: '那条说你开挂的旧帖又被顶了上来，这次你已经是职业选手。', ctx: '当年那件事，你没有正面说清楚。',
    a: [{ t: '开手部摄像头直播一场', g: 'show', e: { heat: 30, fatigue: 5, fans: 10 } },
      { t: '请俱乐部发声明', g: 'warm', e: { gmTrust: -3, heat: 5 } },
      { t: '不理，用下一场说话', g: 'grind', e: { quest: 'rumor' } }] },
  { id: 'echo_notes', w: 0, max: 1, rec: 0, echo: 'notes', when: isStarter,
    q: '对面打出了一套你在替补席上整理过的战术。', ctx: '那份资料是你一条条标出来的。',
    a: [{ t: '暂停时告诉指挥', g: 'warm', e: { coachTrust: 4, form: 2, bond: 3 } },
      { t: '不声张，关键回合自己用上', g: 'hard', e: { form: 3, xp: { awareness: 8 } } }] },
  { id: 'echo_rookie_up', w: 0, max: 1, rec: 1, echo: 'rookie', when: isPro,
    q: '当年你带过复盘的那个新人，拿下了职业生涯第一个 MVP。', ctx: '采访里他说，是你教会了他怎么看录像。',
    a: [{ t: '转发祝贺', g: 'show', e: { heat: 20, mental: 1 } },
      { t: '私下发条消息', g: 'warm', e: { mental: 2, tilt: -4 } }] },
  { id: 'echo_rookie_rival', w: 0, max: 1, rec: 1, echo: 'rookie', when: isPro,
    q: '当年被你在训练赛里压着打的那个新人，现在是别队的首发。', ctx: '赛前采访，他说最想打的就是你。',
    a: [{ t: '回应一个字：「来」', g: 'hard', e: { heat: 35, tilt: 5, form: 1 } },
      { t: '不回应，赛场上见', g: 'grind', e: { mental: 1, form: 1 } },
      { t: '私下跟他说，当年话重了', g: 'warm', e: { tilt: -5, heat: 5 } }] },
  { id: 'echo_home', w: 0, max: 2, rec: 0, echo: 'home', when: () => true,
    q: '你说过打完那个赛段就回家，两个月过去了。', ctx: '妈妈这次没再打电话来问。',
    a: [{ t: '请两天假回去', g: 'warm', e: { fatigue: -10, tilt: -8, mental: 2, coachTrust: -2 } },
      { t: '再往后推', g: 'grind', e: { mental: -2, tilt: 5, xp: { aim: 8 } } },
      { t: '视频通话，答应下个假期一定回', g: 'show', e: { mental: 1 } }] },

  // ---- 合同年 (chain: showcase) — the weeks between the cards are the audition
  { id: 'ch_show_open', w: 0, max: 4, rec: 1, chain: 'showcase', when: (s) => s.me!.chain?.id === 'showcase',
    q: '经纪人发来消息：合同只剩这一季了。', ctx: '经理说续不续约，看接下来这一个多月。',
    a: [{ t: '用正赛说话', g: 'hard', e: { tilt: 3 }, ch: { track: 'win', need: 3, weeks: 3 } },
      { t: '训练赛全勤，让教练天天看见', g: 'grind', e: { fatigue: 3 }, ch: { track: 'scrim', need: 5, weeks: 3 } },
      { t: '不去想，照常打', g: 'warm', e: { tilt: -4, gmTrust: -2 }, ch: { end: 'drop' } }] },
  { id: 'ch_show_mid', w: 0, max: 4, rec: 0, chain: 'showcase', when: (s) => s.me!.chain?.id === 'showcase',
    q: '合同年过半，经理来看了一场训练赛。', ctx: '他没多说，只说再看三周。',
    a: [{ t: '当晚加练一场给他看', g: 'grind', e: { fatigue: 8 }, ch: { add: 1, weeks: 3 } },
      { t: '找经理聊聊你的打算', g: 'warm', e: { gmTrust: 4 }, ch: { weeks: 3 } },
      { t: '让经纪人放风，说有队在问', g: 'show', e: { heat: 15, gmTrust: -5, coachTrust: -2 }, ch: { weeks: 3 } }] },
  { id: 'ch_show_ok', w: 0, max: 4, rec: 1, chain: 'showcase', when: (s) => s.me!.chain?.id === 'showcase',
    q: '经理把你叫进办公室：「续约的事，冬天谈。」', ctx: '这几周他都看在眼里。',
    a: [{ t: '趁热打铁，现在就谈条件', g: 'hard', e: { gmTrust: 4, heat: 10, coachTrust: 2 }, ch: { end: 'ok' } },
      { t: '谢谢，先把赛季打完', g: 'grind', e: { coachTrust: 6, gmTrust: 4, mental: 1 }, ch: { end: 'ok' } }] },
  { id: 'ch_show_miss', w: 0, max: 4, rec: 1, chain: 'showcase', when: (s) => s.me!.chain?.id === 'showcase',
    q: '一个多月过去，经理没再提续约的事。', ctx: '你说过要打给他看的。',
    a: [{ t: '去找经理要个说法', g: 'hard', e: { gmTrust: -4, tilt: 6 }, ch: { end: 'miss' } },
      { t: '闷头练，把剩下的赛季打好', g: 'grind', e: { xp: { aim: 10, awareness: 6 }, fatigue: 8, coachTrust: -3 }, ch: { end: 'miss' } },
      { t: '让经纪人先联系别的队', g: 'show', e: { gmTrust: -8, heat: 15 }, ch: { end: 'miss' } }] },

  // ---- 外区邀约 (chain: overseas) — the answer is an offer at the window, or nothing
  { id: 'ch_abroad_open', w: 0, max: 2, rec: 1, chain: 'overseas', when: (s) => s.me!.chain?.id === 'overseas',
    q: '经纪人转来一封邮件：一家外赛区俱乐部想了解你。', ctx: '他们想约一次视频面谈，你得先把他们的比赛看熟。',
    a: [{ t: '认真准备：补外语，看他们的比赛', g: 'grind', e: { xp: { communication: 8 }, fatigue: 4 }, ch: { track: 'vod', need: 2, weeks: 3, score: 1 } },
      { t: '先告诉经理', g: 'warm', e: { gmTrust: 5 }, ch: { track: 'vod', need: 1, weeks: 3 } },
      { t: '不去，我在这里还没打出来', g: 'hard', e: { coachTrust: 2, mental: 1 }, ch: { end: 'drop' } }] },
  { id: 'ch_abroad_friend', w: 0, max: 1, rec: 1, chain: 'overseas', when: (s) => s.me!.chain?.id === 'overseas',
    q: '国际赛上认识的那个外区选手发来消息：他们队在找你这个位置。', ctx: '他说教练看过你的比赛，想约一次视频面谈。',
    a: [{ t: '认真准备：补外语，看他们的比赛', g: 'grind', e: { xp: { communication: 8 }, fatigue: 4 }, ch: { track: 'vod', need: 2, weeks: 3, score: 2 } },
      { t: '先告诉经理', g: 'warm', e: { gmTrust: 5 }, ch: { track: 'vod', need: 1, weeks: 3, score: 1 } },
      { t: '谢谢他，但不去', g: 'hard', e: { mental: 1 }, ch: { end: 'drop' } }] },
  { id: 'ch_abroad_call', w: 0, max: 2, rec: 1, chain: 'overseas', when: (s) => s.me!.chain?.id === 'overseas',
    q: '视频面谈。对面的主教练问：「你在队里语音说得多吗？」', ctx: '翻译软件开着，但他想听你自己说。',
    a: [{ t: '用外语硬答', g: 'hard', e: { xp: { communication: 12 }, tilt: 3 }, ch: { track: 'window', score: 1 } },
      { t: '请经纪人帮忙翻译', g: 'warm', e: { money: -600 }, ch: { track: 'window' } },
      { t: '说实话：还是想留在本赛区', g: 'grind', e: { gmTrust: 3 }, ch: { end: 'drop' } }] },
  { id: 'ch_abroad_cold', w: 0, max: 2, rec: 0, chain: 'overseas', when: (s) => s.me!.chain?.id === 'overseas',
    q: '面谈那天你没准备好，对方礼貌地结束了通话。', ctx: '消息还是传到了经理那里。',
    a: [{ t: '主动跟经理解释', g: 'warm', e: { gmTrust: -2, mental: 1 }, ch: { end: 'miss' } },
      { t: '不解释', g: 'hard', e: { gmTrust: -6, tilt: -2 }, ch: { end: 'miss' } }] },

  // ---- 直播风波 (chain: storm) — say it, or stay off the air, and then keep to it
  { id: 'ch_storm_open', w: 0, max: 2, rec: 1, chain: 'storm', when: (s) => s.me!.chain?.id === 'storm',
    q: '直播时随口一句吐槽被切了片，挂上了论坛首页。', ctx: '评论两边在吵，热度还在涨。',
    a: [{ t: '这周开播，正面说清楚', g: 'show', e: { heat: 15 }, ch: { track: 'stream', need: 1, weeks: 1 } },
      { t: '冷处理：两周不开播', g: 'grind', e: { heat: -5 }, ch: { track: 'quiet', weeks: 2 } },
      { t: '发文道歉，到此为止', g: 'warm', e: { heat: -10, fans: -15, gmTrust: 2 }, ch: { end: 'drop' } }] },
  { id: 'ch_storm_calm', w: 0, max: 2, rec: 0, chain: 'storm', when: (s) => s.me!.chain?.id === 'storm',
    q: '风头下去了一半，还有人在评论区等你回来。', ctx: '接下来怎么做，决定这事怎么收尾。',
    a: [{ t: '回到直播间，只打游戏不提这事', g: 'grind', e: { mental: 1 }, ch: { track: 'stream', need: 1, weeks: 2 } },
      { t: '再停两周，专心训练', g: 'warm', e: { xp: { aim: 8 } }, ch: { track: 'quiet', weeks: 2 } }] },
  { id: 'ch_storm_flare', w: 0, max: 2, rec: 1, chain: 'storm', when: (s) => s.me!.chain?.id === 'storm',
    q: '切片越传越远，有人翻出了你更早的直播录像。', ctx: '私信和评论一起涌进来。',
    a: [{ t: '开播正面回应', g: 'show', e: { heat: 25, tilt: 8 }, ch: { track: 'stream', need: 1, weeks: 2 } },
      { t: '关掉直播间，先停一段', g: 'grind', e: { heat: -15, fans: -20, tilt: -4 }, ch: { track: 'quiet', weeks: 3 } },
      { t: '发一份正式声明', g: 'warm', e: { heat: -10, fans: -25, gmTrust: 2 }, ch: { end: 'miss' } }] },
  { id: 'ch_storm_ok', w: 0, max: 2, rec: 1, chain: 'storm', when: (s) => s.me!.chain?.id === 'storm',
    q: '那条切片沉下去了，新的热帖把它盖住了。', ctx: '直播间里有人发弹幕：「欢迎回来。」',
    a: [{ t: '自嘲一句，把它变成梗', g: 'show', e: { heat: 25, fans: 15 }, ch: { end: 'ok' } },
      { t: '只字不提，接着打', g: 'grind', e: { mental: 1, tilt: -6 }, ch: { end: 'ok' } }] },
  { id: 'ch_storm_bad', w: 0, max: 2, rec: 0, chain: 'storm', when: (s) => s.me!.chain?.id === 'storm',
    q: '说好的做法没做到，这件事被剪成了「翻车合集」。', ctx: '你的名字后面多了一个外号。',
    a: [{ t: '认了，下次管住嘴', g: 'warm', e: { fans: -30, tilt: 6, mental: 1 }, ch: { end: 'miss' } },
      { t: '拉黑一批人，照常播', g: 'hard', e: { heat: 20, fans: -20, tilt: 10 }, ch: { end: 'miss' } }] },

  // ---- 队内矛盾 (chain: rift) — with one named teammate; ignoring it is the third option, and it comes to a head
  { id: 'ch_rift_open', w: 0, max: 3, rec: 0, chain: 'rift', when: (s) => s.me!.chain?.id === 'rift',
    q: '训练赛第十一回合，你喊强起，一个队友坚持 ECO，语音里吵到教练摘了耳机。', ctx: '散场的时候他没看你。',
    a: [{ t: '当晚找他单聊，约他双排', g: 'warm', e: { tilt: -3 }, ch: { mate: 5, track: 'duo', need: 1, weeks: 2 } },
      { t: '复盘会上放录像，让数据说话', g: 'hard', e: { xp: { awareness: 8 }, coachTrust: 2 }, ch: { mate: -4, track: 'scrim', need: 2, weeks: 2 } },
      { t: '各打各的', g: 'grind', e: { tilt: 2 }, ch: { mate: -2, track: 'duo', need: 1, weeks: 2 } }] },
  { id: 'ch_rift_thaw', w: 0, max: 3, rec: 0, chain: 'rift', when: (s) => s.me!.chain?.id === 'rift',
    q: '这几天训练赛里你们配合上了几次，他在群里给你的集锦点了个赞。', ctx: '冰还没完全化开。',
    a: [{ t: '请他吃顿夜宵，把话说开', g: 'warm', e: { money: -200, tilt: -3 }, ch: { mate: 8, track: 'duo', need: 1, weeks: 2 } },
      { t: '把那个回合做成战术，下次一起用', g: 'grind', e: { xp: { teamwork: 10 } }, ch: { mate: 4, track: 'scrim', need: 2, weeks: 2 } }] },
  { id: 'ch_rift_boil', w: 0, max: 3, rec: 0, chain: 'rift', when: (s) => s.me!.chain?.id === 'rift',
    q: '矛盾没过去：他在复盘会上当着全队说，那回合输在你身上。', ctx: '教练看着你们两个。',
    a: [{ t: '当场认下，先把队伍放前面', g: 'warm', e: { tilt: 4, coachTrust: 3 }, ch: { mate: 6, track: 'duo', need: 1, weeks: 2 } },
      { t: '顶回去，把录像再放一遍', g: 'hard', e: { tilt: 8, coachTrust: -3 }, ch: { mate: -8, track: 'scrim', need: 3, weeks: 2 } },
      { t: '请教练把你们分进不同的训练组', g: 'grind', e: { coachTrust: -2, xp: { aim: 8 } }, ch: { mate: -3, end: 'miss' } }] },
  { id: 'ch_rift_ok', w: 0, max: 3, rec: 1, chain: 'rift', when: (s) => s.me!.chain?.id === 'rift',
    q: '训练赛的残局里，他把最后一个敌人的位置报给了你。', ctx: '打完他拍了拍你的肩膀。',
    a: [{ t: '当着全队把功劳给他', g: 'warm', e: { tilt: -4, bond: 3 }, ch: { mate: 10, end: 'ok' } },
      { t: '什么都不说，接着打', g: 'grind', e: { form: 2, mental: 1 }, ch: { mate: 6, end: 'ok' } }] },
  { id: 'ch_rift_bad', w: 0, max: 3, rec: 0, chain: 'rift', when: (s) => s.me!.chain?.id === 'rift',
    q: '队里的气氛到了教练必须出面的地步。', ctx: '他把你们两个叫进了办公室。',
    a: [{ t: '主动让步', g: 'warm', e: { tilt: -6, coachTrust: 2, form: -2 }, ch: { mate: 4, end: 'miss' } },
      { t: '「有他没我。」', g: 'hard', e: { coachTrust: -8, tilt: 10, heat: 10 }, ch: { mate: -10, end: 'miss' } },
      { t: '一句话都不说', g: 'grind', e: { coachTrust: -4, morale: -8 }, ch: { end: 'miss' } }] },
]
