/**
 * The official top-down minimaps, clean, with only the site letters — and
 * where the sites and both spawns sit on each image.
 *
 * Source: valorant-api.com (the same place the agent names came from). Each
 * map ships a displayicon.png plus the transform that turns a game location
 * into a fraction of that image (x on the image is the game's y, and the
 * other way round — that is how the API defines it), and a callout list
 * that includes "A Site", "Attacker Side Spawn" and so on.
 *
 *   npx tsx scripts/fetch_minimaps.ts
 *
 * Writes public/minimaps/<Map>.png and src/data/minimaps.ts. Re-run when a
 * map is added or Riot redraws one.
 */
import { mkdirSync, writeFileSync } from 'node:fs'

const WANT = ['Ascent', 'Bind', 'Breeze', 'Corrode', 'Fracture', 'Haven', 'Icebox', 'Lotus', 'Pearl', 'Split', 'Summit', 'Sunset', 'Abyss']

interface Callout { regionName: string; superRegionName: string; location: { x: number; y: number } }
interface ApiMap {
  displayName: string; displayIcon: string | null
  xMultiplier: number; yMultiplier: number; xScalarToAdd: number; yScalarToAdd: number
  callouts: Callout[] | null
}

const res = await fetch('https://valorant-api.com/v1/maps')
const maps = ((await res.json()) as { data: ApiMap[] }).data
mkdirSync('public/minimaps', { recursive: true })

const out: Record<string, { sites: Record<string, [number, number]>; atk: [number, number]; def: [number, number] }> = {}
let total = 0
for (const m of maps) {
  if (!WANT.includes(m.displayName) || !m.displayIcon) continue
  const png = Buffer.from(await (await fetch(m.displayIcon)).arrayBuffer())
  writeFileSync(`public/minimaps/${m.displayName}.png`, png)
  total += png.length
  const toImg = (loc: { x: number; y: number }): [number, number] => [
    Math.round((loc.y * m.xMultiplier + m.xScalarToAdd) * 1000) / 10,
    Math.round((loc.x * m.yMultiplier + m.yScalarToAdd) * 1000) / 10,
  ]
  const sites: Record<string, [number, number]> = {}
  let atk: [number, number] = [50, 92]
  let def: [number, number] = [50, 8]
  for (const c of m.callouts ?? []) {
    if (c.regionName === 'Site' && ['A', 'B', 'C'].includes(c.superRegionName)) sites[c.superRegionName] = toImg(c.location)
    if (c.regionName === 'Spawn') {
      if (c.superRegionName.startsWith('Attacker')) atk = toImg(c.location)
      if (c.superRegionName.startsWith('Defender')) def = toImg(c.location)
    }
  }
  out[m.displayName] = { sites, atk, def }
  console.log(`${m.displayName.padEnd(9)} ${(png.length / 1024).toFixed(0).padStart(4)} KB  sites ${JSON.stringify(sites)}  atk ${JSON.stringify(atk)} def ${JSON.stringify(def)}`)
}
console.log(`total ${(total / 1024 / 1024).toFixed(2)} MB`)

const ts = `/**
 * Where the sites and spawns sit on each official minimap, as percentages of
 * the image. Generated by scripts/fetch_minimaps.ts from valorant-api.com —
 * do not edit by hand, re-run the script.
 */
export type MiniPt = [number, number]
export interface MiniMap { sites: Record<string, MiniPt>; atk: MiniPt; def: MiniPt }
export const MINIMAPS: Record<string, MiniMap> = ${JSON.stringify(out, null, 2)}
`
writeFileSync('src/data/minimaps.ts', ts)
