"""Generate the QR matrix that the career card draws.

The card is drawn on a <canvas>, and the page's CSP will not load an external
script, so the QR cannot be produced in the browser by a library. It also
should not be a base64 PNG: a small bitmap scaled up on canvas goes soft, and
a blob is impossible to review in a diff.

So the matrix is generated here, once, by a real QR library, and committed as
a run-length string that src/ui/me/share.ts expands and draws as crisp
squares at whatever size the card needs.

    pip install qrcode
    python scripts/make_qr.py https://valplayer-production.up.railway.app

Prints a TypeScript literal to paste into share.ts. Re-run it if the URL
changes — the matrix is the URL, and a stale one sends people somewhere else.
"""
import sys

import qrcode

url = sys.argv[1] if len(sys.argv) > 1 else 'https://valplayer-production.up.railway.app'

q = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, box_size=1, border=0)
q.add_data(url)
q.make(fit=True)
m = q.get_matrix()
n = len(m)

bits = ''.join('1' if c else '0' for row in m for c in row)
assert len(bits) == n * n

# run-length: alternating counts of 0s then 1s, starting with 0s
runs, cur, count = [], '0', 0
for b in bits:
    if b == cur:
        count += 1
    else:
        runs.append(count)
        cur = b
        count = 1
runs.append(count)

print(f'/** {url} — QR version {q.version}, EC level M, {n}x{n}.')
print(' *  Generated by scripts/make_qr.py; regenerate it if the URL changes. */')
print(f"export const QR_URL = '{url}'")
print(f'export const QR_SIZE = {n}')
print(f"export const QR_RUNS = '{','.join(str(r) for r in runs)}'")
print()
print('// preview:')
for row in m:
    print('// ' + ''.join('##' if c else '  ' for c in row))
