/**
 * Where the sites and spawns sit on each official minimap, as percentages of
 * the image. Generated by scripts/fetch_minimaps.ts from valorant-api.com —
 * do not edit by hand, re-run the script.
 */
export type MiniPt = [number, number]
export interface MiniMap { sites: Record<string, MiniPt>; atk: MiniPt; def: MiniPt }
export const MINIMAPS: Record<string, MiniMap> = {
  "Ascent": {
    "sites": {
      "A": [
        35,
        14.2
      ],
      "B": [
        28.5,
        73.7
      ]
    },
    "atk": [
      81.7,
      56.9
    ],
    "def": [
      13.2,
      43.4
    ]
  },
  "Split": {
    "sites": {
      "A": [
        31.5,
        18.4
      ],
      "B": [
        35.4,
        86.7
      ]
    },
    "atk": [
      84.7,
      54.9
    ],
    "def": [
      14.3,
      53
    ]
  },
  "Fracture": {
    "sites": {
      "B": [
        9.3,
        51.8
      ],
      "A": [
        82,
        52.2
      ]
    },
    "atk": [
      48.3,
      81.7
    ],
    "def": [
      50.4,
      44.2
    ]
  },
  "Bind": {
    "sites": {
      "A": [
        73.4,
        33.3
      ],
      "B": [
        29.2,
        31.2
      ]
    },
    "atk": [
      58.2,
      95.8
    ],
    "def": [
      51.7,
      10.4
    ]
  },
  "Breeze": {
    "sites": {
      "B": [
        7,
        38.2
      ],
      "A": [
        90.8,
        49.5
      ]
    },
    "atk": [
      43.4,
      87.3
    ],
    "def": [
      71.2,
      21
    ]
  },
  "Abyss": {
    "sites": {
      "A": [
        48.4,
        15.2
      ],
      "B": [
        40.5,
        85.8
      ]
    },
    "atk": [
      90.1,
      42.3
    ],
    "def": [
      7.3,
      42.3
    ]
  },
  "Lotus": {
    "sites": {
      "A": [
        85.5,
        36.1
      ],
      "B": [
        50.3,
        45.9
      ],
      "C": [
        14.8,
        43.7
      ]
    },
    "atk": [
      51.1,
      81.7
    ],
    "def": [
      57.7,
      22
    ]
  },
  "Sunset": {
    "sites": {
      "B": [
        4.4,
        56.2
      ],
      "A": [
        75,
        43.8
      ]
    },
    "atk": [
      46.9,
      98.6
    ],
    "def": [
      34.5,
      21.9
    ]
  },
  "Pearl": {
    "sites": {
      "A": [
        91.5,
        40
      ],
      "B": [
        25.8,
        46.4
      ]
    },
    "atk": [
      43.4,
      95.9
    ],
    "def": [
      51,
      5.1
    ]
  },
  "Summit": {
    "sites": {
      "A": [
        91.7,
        40.3
      ],
      "B": [
        15.1,
        33.8
      ]
    },
    "atk": [
      4,
      89.6
    ],
    "def": [
      51.1,
      7.3
    ]
  },
  "Icebox": {
    "sites": {
      "A": [
        69.1,
        76.5
      ],
      "B": [
        64.6,
        18
      ]
    },
    "atk": [
      14,
      58.7
    ],
    "def": [
      97,
      57.5
    ]
  },
  "Corrode": {
    "sites": {
      "A": [
        39.8,
        25.8
      ],
      "B": [
        44.4,
        69
      ]
    },
    "atk": [
      92.3,
      50.2
    ],
    "def": [
      12.4,
      49.9
    ]
  },
  "Haven": {
    "sites": {
      "A": [
        40.2,
        17
      ],
      "B": [
        40.1,
        50.1
      ],
      "C": [
        41.8,
        82.1
      ]
    },
    "atk": [
      89.5,
      51.2
    ],
    "def": [
      14,
      42.2
    ]
  }
}
